### ISSUE TITLE
spl won't compile on kernel 3.1.6 error: too few arguments to function 'filp->f_op->fsync'

### ISSUE THREAD

**Issue by TvL2386** [Pinkbyte/pinkbyte-overlay#2]
Hi! Thank you very much for providing your overlay.
The gentoo zfs wiki tells to use your overlay but it won't install on an up to date box.

```

cat /var/tmp/portage/sys-devel/spl-0.6.0_rc6/temp/build.log
 * Package:    sys-devel/spl-0.6.0_rc6
 * Repository: pinkbyte
 * USE:        amd64 elibc_glibc kernel_linux multilib userland_GNU
 * FEATURES:   sandbox
 * Determining the location of the kernel source code
 * Found kernel source directory:
 *     /usr/src/linux
 * Found kernel object directory:
 *     /lib/modules/3.1.6-gentoo/build
 * Found sources for kernel version:
 *     3.1.6-gentoo
>>> Unpacking source...
>>> Unpacking spl-0.6.0-rc6.tar.gz to /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work
>>> Source unpacked in /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work
>>> Preparing source in /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6 ...
 * Applying spl-0.6.0-includedir.patch ...                               [ ok ]
 * Running eautoreconf in '/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6' ...
 * Running aclocal -I ./config ...                                       [ ok ]
 * Running libtoolize --copy --force --install --automake ...            [ ok ]
 * Running aclocal -I ./config ...                                       [ ok ]
 * Running autoconf -I ./config ...                                      [ ok ]
 * Running autoheader -I ./config ...                                    [ ok ]
 * Running automake --add-missing --copy --foreign ...                   [ ok ]
 * Running elibtoolize in: spl-0.6.0-rc6/config/
 *   Applying portage/1.2.0 patch ...
 *   Applying sed/1.5.6 patch ...
 *   Applying as-needed/2.2.6 patch ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6 ...
 * econf: updating spl-0.6.0-rc6/config/config.guess with /usr/share/gnuconfig/config.guess
 * econf: updating spl-0.6.0-rc6/config/config.sub with /usr/share/gnuconfig/config.sub
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --libdir=/usr/lib64 --with-config=all --with-linux=/usr/src/linux --with-linux-obj=/usr/src/linux
checking metadata... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for x86_64-pc-linux-gnu-gcc... x86_64-pc-linux-gnu-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-pc-linux-gnu-gcc accepts -g... yes
checking for x86_64-pc-linux-gnu-gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of x86_64-pc-linux-gnu-gcc... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by x86_64-pc-linux-gnu-gcc... /usr/x86_64-pc-linux-gnu/bin/ld
checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-pc-linux-gnu/bin/ld option to reload object files... -r
checking for x86_64-pc-linux-gnu-objdump... x86_64-pc-linux-gnu-objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-pc-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-pc-linux-gnu-ar... x86_64-pc-linux-gnu-ar
checking for archiver @FILE support... @
checking for x86_64-pc-linux-gnu-strip... x86_64-pc-linux-gnu-strip
checking for x86_64-pc-linux-gnu-ranlib... x86_64-pc-linux-gnu-ranlib
checking command to parse /usr/bin/nm -B output from x86_64-pc-linux-gnu-gcc object... ok
checking for sysroot... no
checking for x86_64-pc-linux-gnu-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... x86_64-pc-linux-gnu-gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if x86_64-pc-linux-gnu-gcc supports -fno-rtti -fno-exceptions... no
checking for x86_64-pc-linux-gnu-gcc option to produce PIC... -fPIC -DPIC
checking if x86_64-pc-linux-gnu-gcc PIC flag -fPIC -DPIC works... yes
checking if x86_64-pc-linux-gnu-gcc static flag -static works... yes
checking if x86_64-pc-linux-gnu-gcc supports -c -o file.o... yes
checking if x86_64-pc-linux-gnu-gcc supports -c -o file.o... (cached) yes
checking whether the x86_64-pc-linux-gnu-gcc linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking spl license... GPL
checking whether rpm is available... no
checking whether rpmbuild is available... no
checking whether dpkg is available... no
checking whether dpkg-buildpackage is available... no
checking whether alien is available... no
checking linux distribution... gentoo
checking default package type... rpm
checking spl config... all
checking kernel source directory... /usr/src/linux
checking kernel build directory... /usr/src/linux
checking kernel source version... 3.1.6-gentoo
checking kernel file name for module symbols... Module.symvers
checking whether Linux was built with CONFIG_PREEMPT... no
checking whether debugging is enabled... no
checking whether basic kmem accounting is enabled... yes
checking whether detailed kmem tracking is enabled... no
checking whether atomic types use spinlocks... no
checking whether kernel defines atomic64_t... yes
checking whether kernel defines atomic64_cmpxchg... yes
checking whether kernel defines atomic64_xchg... yes
checking whether kernel defines uintptr_t... yes
checking whether INIT_WORK wants 3 args... no
checking whether register_sysctl_table() wants 2 args... no
checking whether set_shrinker() available... no
checking whether shrinker callback wants 3 args... no
checking whether struct path used in struct nameidata... yes
checking whether symbol task_curr is exported... no
checking whether unnumbered sysctl support exists... no
checking whether struct ctl_table has ctl_name... no
checking whether fls64() is available... yes
checking whether symbol device_create is exported... yes
checking whether device_create() wants 5 args... yes
checking whether symbol class_device_create is exported... no
checking whether symbol set_normalized_timespec is exported... yes
checking whether set_normalized_timespec() is an inline... yes
checking whether timespec_sub() is available... yes
checking whether init_utsname() is available... yes
checking whether header linux/fdtable.h exists... yes
checking whether files_fdtable() is available... yes
checking whether header linux/uaccess.h exists... yes
checking whether kmalloc_node() is available... yes
checking whether symbol monotonic_clock is exported... no
checking whether struct inode has i_mutex... yes
checking whether struct mutex has owner... yes
checking whether struct mutex owner is a task_struct... yes
checking whether mutex_lock_nested() is available... yes
checking whether on_each_cpu() wants 3 args... yes
checking whether symbol kallsyms_lookup_name is exported... yes
checking whether symbol get_vmalloc_info is exported... no
checking whether symbol *_pgdat exist... yes
checking whether symbol first_online_pgdat is exported... no
checking whether symbol next_online_pgdat is exported... no
checking whether symbol next_zone is exported... no
checking whether symbol pgdat_list is exported... no
checking whether global_page_state() is available... yes
checking whether page state NR_FREE_PAGES is available... yes
checking whether page state NR_INACTIVE is available... no
checking whether page state NR_INACTIVE_ANON is available... yes
checking whether page state NR_INACTIVE_FILE is available... yes
checking whether page state NR_ACTIVE is available... no
checking whether page state NR_ACTIVE_ANON is available... yes
checking whether page state NR_ACTIVE_FILE is available... yes
checking whether symbol get_zone_counts is needed... no
checking whether symbol user_path_at is exported... yes
checking whether symbol set_fs_pwd is exported... no
checking whether set_fs_pwd() wants 2 args... yes
checking whether vfs_unlink() wants 2 args... yes
checking whether vfs_rename() wants 4 args... yes
checking whether struct fs_struct uses spinlock_t... yes
checking whether struct cred exists... yes
checking whether symbol groups_search is exported... no
checking whether symbol __put_task_struct is exported... yes
checking whether proc_handler() wants 5 args... yes
checking whether symbol kvasprintf is exported... yes
checking whether file_fsync() wants 3 args... no
checking whether symbol rwsem_is_locked is exported... yes
checking whether symbol invalidate_inodes is exported... no
checking whether invalidate_inodes() wants 2 args... yes
checking whether symbol shrink_dcache_memory is exported... no
checking whether symbol shrink_icache_memory is exported... no
checking whether symbol kern_path_parent is exported... no
checking whether zlib_deflate_workspacesize() wants 2 args... yes
checking whether struct shrink_control exists... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating cmd/Makefile
config.status: creating module/Makefile
config.status: creating module/spl/Makefile
config.status: creating module/splat/Makefile
config.status: creating include/Makefile
config.status: creating scripts/Makefile
config.status: creating spl.spec
config.status: creating spl-modules.spec
config.status: creating spl_config.h
config.status: executing depfiles commands
config.status: executing libtool commands
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6 ...
make -j3
make  all-recursive
make[1]: Entering directory `/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6'
Making all in lib
make[2]: Entering directory `/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/lib'
/bin/sh ../libtool  --tag=CC --silent  --mode=compile x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -include ../spl_config.h    -Wall -Wshadow -Wstrict-prototypes -fno-strict-aliasing -D__USE_LARGEFILE64 -DNDEBUG -O2 -pipe -MT list.lo -MD -MP -MF .deps/list.Tpo -c -o list.lo list.c
mv -f .deps/list.Tpo .deps/list.Plo
/bin/sh ../libtool  --tag=CC --silent  --mode=link x86_64-pc-linux-gnu-gcc -Wall -Wshadow -Wstrict-prototypes -fno-strict-aliasing -D__USE_LARGEFILE64 -DNDEBUG -O2 -pipe  -Wl,-O1 -Wl,--as-needed -o libcommon.la  list.lo
make[2]: Leaving directory `/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/lib'
Making all in cmd
make[2]: Entering directory `/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/cmd'
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -include ../spl_config.h -I../lib    -Wall -Wshadow -Wstrict-prototypes -fno-strict-aliasing -D__USE_LARGEFILE64 -DNDEBUG -O2 -pipe -MT spl.o -MD -MP -MF .deps/spl.Tpo -c -o spl.o spl.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -include ../spl_config.h -I../lib    -Wall -Wshadow -Wstrict-prototypes -fno-strict-aliasing -D__USE_LARGEFILE64 -DNDEBUG -O2 -pipe -MT splat.o -MD -MP -MF .deps/splat.Tpo -c -o splat.o splat.c
mv -f .deps/spl.Tpo .deps/spl.Po
/bin/sh ../libtool  --tag=CC --silent  --mode=link x86_64-pc-linux-gnu-gcc -Wall -Wshadow -Wstrict-prototypes -fno-strict-aliasing -D__USE_LARGEFILE64 -DNDEBUG -O2 -pipe  -Wl,-O1 -Wl,--as-needed -o spl spl.o
mv -f .deps/splat.Tpo .deps/splat.Po
/bin/sh ../libtool  --tag=CC --silent  --mode=link x86_64-pc-linux-gnu-gcc -Wall -Wshadow -Wstrict-prototypes -fno-strict-aliasing -D__USE_LARGEFILE64 -DNDEBUG -O2 -pipe ../lib/libcommon.la -Wl,-O1 -Wl,--as-needed -o splat splat.o
make[2]: Leaving directory `/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/cmd'
Making all in scripts
make[2]: Entering directory `/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/scripts'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/scripts'
Making all in module
make[2]: Entering directory `/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module'
make -C /usr/src/linux SUBDIRS=`pwd`  modules
make[3]: Entering directory `/usr/src/linux-3.1.6-gentoo'
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/spl/../../module/spl/spl-debug.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-ctl.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/spl/../../module/spl/spl-proc.o
/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/spl/../../module/spl/spl-debug.c: In function 'spl_debug_dump_all_pages':
/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/spl/../../module/spl/spl-debug.c:963:9: error: too few arguments to function 'filp->f_op->fsync'
make[5]: *** [/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/spl/../../module/spl/spl-debug.o] Error 1
make[5]: *** Waiting for unfinished jobs....
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-kmem.o
make[4]: *** [/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/spl] Error 2
make[4]: *** Waiting for unfinished jobs....
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-taskq.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-random.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-mutex.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-condvar.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-thread.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-rwlock.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-time.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-vnode.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-kobj.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-atomic.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-list.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-generic.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-cred.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-zlib.o
  CC [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/../../module/splat/splat-linux.o
  LD [M]  /var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module/splat/splat.o
make[3]: *** [_module_/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module] Error 2
make[3]: Leaving directory `/usr/src/linux-3.1.6-gentoo'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6'
make: *** [all] Error 2
emake failed
 * ERROR: sys-devel/spl-0.6.0_rc6 failed (compile phase):
 *   emake failed
 *
 * Call stack:
 *          ebuild.sh, line   75:  Called src_compile
 *        environment, line 3409:  Called _eapi2_src_compile
 *   phase-helpers.sh, line  577:  Called die
 * The specific snippet of code:
 *              emake || die "emake failed"
 *
 * If you need support, post the output of 'emerge --info =sys-devel/spl-0.6.0_rc6',
 * the complete build log and the output of 'emerge -pqv =sys-devel/spl-0.6.0_rc6'.
 * This ebuild is from an overlay named 'pinkbyte': '/var/lib/layman/pinkbyte/'
 * The complete build log is located at '/var/tmp/portage/sys-devel/spl-0.6.0_rc6/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sys-devel/spl-0.6.0_rc6/temp/environment'.
 * S: '/var/tmp/portage/sys-devel/spl-0.6.0_rc6/work/spl-0.6.0-rc6'
pollux ~ #
```
